"""Integration tests for threatlens.network.detector + SHAP explainer.

These tests require the trained artefacts in `results/cicids2017/` to exist
(generated by `python -m threatlens.ml.train`). They also require a small
slice of the CIC-IDS2017 CSVs — we synthesize valid-looking rows by reading
the first few PortScan/BENIGN rows of the dataset if present, and skip the
test otherwise.
"""

import os

import pandas as pd
import pytest

from threatlens.network import FlowDetector, CIC_FEATURE_COLUMNS


RESULTS_DIR = os.path.join(os.path.dirname(__file__), "..", "results", "cicids2017")
PORTSCAN_CSV = os.path.join(
    os.path.dirname(__file__), "..", "data", "cicids2017",
    "Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv",
)


@pytest.fixture(scope="module")
def detector():
    if not os.path.exists(os.path.join(RESULTS_DIR, "xgboost.joblib")):
        pytest.skip("trained models not present — run `python -m threatlens.ml.train` first")
    return FlowDetector.from_results_dir(RESULTS_DIR)


@pytest.fixture(scope="module")
def portscan_slice():
    """Real CIC-IDS2017 rows (genuine attack + benign) for regression testing."""
    if not os.path.exists(PORTSCAN_CSV):
        pytest.skip("CIC-IDS2017 CSVs not downloaded; see data/cicids2017/README")
    df = pd.read_csv(PORTSCAN_CSV, nrows=200_000, low_memory=False)
    df.columns = [c.strip() for c in df.columns]
    benign = df[df["Label"] == "BENIGN"].head(20)
    portscan = df[df["Label"] == "PortScan"].head(20)
    return pd.concat([benign, portscan], ignore_index=True)


# ---------------------------------------------------------------------------
# Minimal contract tests — detector loads and predicts on a synthetic row
# ---------------------------------------------------------------------------


def test_detector_loads_all_artefacts(detector):
    assert detector._models["xgboost"] is not None
    assert detector._models["random_forest"] is not None
    assert detector._isolation is not None
    assert detector._pipeline is not None
    assert len(detector._pipeline.feature_names) == 70


def test_detector_predict_on_empty_dataframe(detector):
    empty = pd.DataFrame(columns=CIC_FEATURE_COLUMNS)
    out = detector.predict(empty)
    assert out.empty


def test_detector_predict_returns_expected_columns(detector):
    row = {c: 0.0 for c in CIC_FEATURE_COLUMNS}
    row.update({"src_ip": "1.2.3.4", "dst_ip": "5.6.7.8", "src_port": 12345, "protocol": 6})
    df = pd.DataFrame([row])
    out = detector.predict(df)
    for col in ("label", "is_attack", "confidence", "anomaly_score", "anomaly_flag"):
        assert col in out.columns


def test_detector_summary_buckets_by_protocol_and_timeline(detector):
    rows = []
    for proto in (6, 17, 6):
        r = {c: 0.0 for c in CIC_FEATURE_COLUMNS}
        r.update({
            "src_ip": "1.2.3.4", "dst_ip": "5.6.7.8",
            "src_port": 12345, "protocol": proto, "timestamp": 1_700_000_000.0 + proto,
        })
        rows.append(r)
    preds = detector.predict(pd.DataFrame(rows))
    summary = detector.summary(preds)
    assert summary["total_flows"] == 3
    assert set(summary["protocols"]) == {"TCP", "UDP"}
    assert summary["protocols"]["TCP"] == 2


# ---------------------------------------------------------------------------
# Regression tests against real CIC-IDS2017 rows
# ---------------------------------------------------------------------------


def test_detector_recognises_portscan_rows_above_threshold(detector, portscan_slice):
    """On real CIC-IDS2017 PortScan rows the classifier should at least
    flag the majority as attacks — matching our published F1 metric."""
    attacks = portscan_slice[portscan_slice["Label"] == "PortScan"]
    preds = detector.predict(attacks)
    flagged = (preds["is_attack"] == 1).sum()
    assert flagged >= len(attacks) * 0.5, \
        f"Expected >=50% of real PortScan rows flagged, got {flagged}/{len(attacks)}"


def test_shap_explanation_returns_topk_features(detector):
    flow = {c: 0.0 for c in CIC_FEATURE_COLUMNS}
    flow["Destination Port"] = 80
    flow["Init_Win_bytes_forward"] = 29200
    flow["Total Fwd Packets"] = 6
    out = detector.explain_shap(flow, top_k=5)
    assert out["model"] == "xgboost"
    assert out["predicted_class"]
    assert len(out["contributions"]) == 5
    for c in out["contributions"]:
        assert set(c) == {"feature", "shap_value", "feature_value"}
        assert c["feature"] in detector._pipeline.feature_names


def test_shap_top_k_is_clamped(detector):
    flow = {c: 0.0 for c in CIC_FEATURE_COLUMNS}
    out = detector.explain_shap(flow, top_k=999)
    # Request clamped to [1, 30]; we have 70 features so 30 is the hard cap.
    assert 1 <= len(out["contributions"]) <= 30


def test_shap_rejects_unknown_model(detector):
    flow = {c: 0.0 for c in CIC_FEATURE_COLUMNS}
    with pytest.raises(ValueError):
        detector.explain_shap(flow, model="not_a_real_model")
