"""Day 9 — train an XGBoost on Python-extracted features ONLY.

Day 7 proved a 90 %+ feature-distribution gap between Java (training)
and Python (inference) cicflowmeter. Day 8 selective prediction
treated this as something to flag rather than fix. Day 9 attacks the
root cause: drop the Java-extracted CIC-2017 / CIC-2018 CSVs from
training entirely and rebuild the model only on data extracted by
the same Python pipeline that will run at inference.

Training data:
  - synthetic_flows.csv (143K Python-extracted flows, 6 classes)
  - 70% of CTU-13 botnet PCAPs (Python-extracted via FlowExtractor,
    label = "Bot"). Held-out 30% goes into the test set.

Test data:
  - real_pcap/ (9 Stratosphere/Wireshark captures, never seen during
    training; the 347-attack benchmark that was 0% recall on the
    Java-trained model).
  - 30% CTU-13 hold-out.

If drift was the dominant cause of real-world miss, recall should
jump from ~10% (Day 6) to a much higher number with this model.
If drift was only PART of the cause, we'll see a lift but not a
victory.

Saves to results/python_only/ — production stays untouched.

Usage:
    python scripts/train_python_only.py
"""
from __future__ import annotations

import argparse
import json
import logging
import sys
import time
from pathlib import Path

import joblib
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from threatlens.network.flow_extractor import (  # noqa: E402
    FlowExtractor, CIC_FEATURE_COLUMNS,
)
from threatlens.network.spectral_features import SPECTRAL_FEATURE_COLUMNS  # noqa: E402
from threatlens.network.payload_yara import YARA_FEATURE_COLUMNS  # noqa: E402
from threatlens.ml.features import FeaturePipeline  # noqa: E402
from threatlens.ml.models import build_xgboost  # noqa: E402

logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger("train_python_only")

ALL_FEATURES = (list(CIC_FEATURE_COLUMNS) + list(SPECTRAL_FEATURE_COLUMNS)
                + list(YARA_FEATURE_COLUMNS))
SYNTHETIC_CSV = ROOT / "data" / "synthetic" / "synthetic_flows.csv"
CTU_DIR = ROOT / "data" / "ctu_malware"
CACHE_PARQUET = ROOT / "results" / "real_world_flows_cache.parquet"
OUT_DIR = ROOT / "results" / "python_only"
# Day 9b: diverse-benign Python-extracted flows generated by
# scripts/generate_diverse_benign.py + scripts/extract_diverse_benign.py.
# Day 9d adds mDNS/DHCP/NTP/SSDP coverage so the model knows what real
# benign internet traffic looks like (not just synthetic curl-FTP/HTTP).
DIVERSE_BENIGN_PARQUET = OUT_DIR / "diverse_benign_flows.parquet"
# Day 9d: high-volume SSH-Patator + FTP-Patator brute-force flows generated
# by scripts/generate_attack_volume.py + scripts/extract_attack_volume.py.
# Fixes the 27-sample SSH-Patator generalisation gap (slips_ssh-bruteforce
# was only 58 % recall before this).
ATTACK_VOLUME_PARQUET = OUT_DIR / "attack_volume_flows.parquet"
# Day 13: real-world modern-malware PCAPs ingested from Stratosphere
# (CTU-Malware-Capture-* 2024-2025 directories) and
# malware-traffic-analysis.net (Lumma / Cobalt Strike / NetSupport / etc.).
# Populated by scripts/ingest_sandbox_pcaps.py + extract_sandbox_pcaps.py.
# Same label schema — most modern C2 families map to "Bot".
SANDBOX_MALWARE_PARQUET = OUT_DIR / "sandbox_malware_flows.parquet"


def load_synthetic_with_cap(hulk_cap: int, random_state: int) -> pd.DataFrame:
    df = pd.read_csv(SYNTHETIC_CSV, low_memory=False)
    df["Label"] = df["Label"].astype(str).str.strip()
    hulk_mask = df["Label"] == "DoS Hulk"
    if hulk_cap > 0 and hulk_mask.sum() > hulk_cap:
        df = pd.concat([df[~hulk_mask],
                        df[hulk_mask].sample(n=hulk_cap, random_state=random_state)],
                       ignore_index=True)
    df["__split_source"] = "synthetic"
    return df


def load_diverse_benign() -> pd.DataFrame:
    """Day 9b/d — Python-crafted DNS/TLS/HTTP/SSH/SMTP/mDNS/DHCP/NTP benign flows.

    Returns empty if the parquet hasn't been generated yet (training will
    fall back to synthetic-only benign).
    """
    if not DIVERSE_BENIGN_PARQUET.exists():
        print(f"[warn] {DIVERSE_BENIGN_PARQUET} not found — skipping diverse benign")
        return pd.DataFrame()
    df = pd.read_parquet(DIVERSE_BENIGN_PARQUET)
    df = df.convert_dtypes(dtype_backend="numpy_nullable")
    df["Label"] = "BENIGN"
    df["__split_source"] = "diverse_benign"
    return df


def load_attack_volume() -> pd.DataFrame:
    """Day 9d — high-volume hydra-style SSH/FTP brute-force flows.

    Adds ~1000 SSH-Patator and ~1000 FTP-Patator samples to remedy the
    27/48-sample generalisation gap from the original synthetic data.
    """
    if not ATTACK_VOLUME_PARQUET.exists():
        print(f"[warn] {ATTACK_VOLUME_PARQUET} not found — skipping attack-volume")
        return pd.DataFrame()
    df = pd.read_parquet(ATTACK_VOLUME_PARQUET)
    df = df.convert_dtypes(dtype_backend="numpy_nullable")
    df["__split_source"] = "attack_volume"
    return df


def load_sandbox_malware() -> pd.DataFrame:
    """Day 13 — modern-era (2024-2026) malware PCAPs from public sandboxes.

    Produced by scripts/ingest_sandbox_pcaps.py + extract_sandbox_pcaps.py.
    Skipped silently if the parquet hasn't been generated yet — the rest of
    the pipeline falls back to the existing synthetic + CTU-13 corpus.
    """
    if not SANDBOX_MALWARE_PARQUET.exists():
        print(f"[warn] {SANDBOX_MALWARE_PARQUET} not found — skipping sandbox-malware")
        return pd.DataFrame()
    df = pd.read_parquet(SANDBOX_MALWARE_PARQUET)
    df = df.convert_dtypes(dtype_backend="numpy_nullable")
    df["__split_source"] = "sandbox_malware"
    return df


def get_ctu_flows_from_cache() -> pd.DataFrame:
    """Load the CTU flows we already extracted in Day 8 (cached parquet).

    Coerce out of PyArrow-backed dtypes — sklearn's stratified split
    chokes on Arrow ChunkedArrays when mixed with numpy arrays from CSV.
    """
    if not CACHE_PARQUET.exists():
        raise FileNotFoundError(
            f"Run scripts/eval_selective_sweep.py first to cache real-world "
            f"flows; missing {CACHE_PARQUET}"
        )
    cache = pd.read_parquet(CACHE_PARQUET, dtype_backend="numpy_nullable")
    # Convert nullable types back to plain numpy
    cache = cache.convert_dtypes(dtype_backend="numpy_nullable").astype({
        c: "float64" for c in cache.columns if cache[c].dtype.kind in "fiub"
    }, errors="ignore")
    ctu = cache[cache["__source"].str.startswith("botnet-")].copy()
    ctu["Label"] = "Bot"  # CTU-13 botnet captures are all-malicious by construction
    return ctu


def main() -> int:
    if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")

    parser = argparse.ArgumentParser()
    parser.add_argument("--hulk-cap", type=int, default=10_000)
    parser.add_argument("--ctu-train-frac", type=float, default=0.70)
    parser.add_argument("--random-state", type=int, default=42)
    args = parser.parse_args()

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    t0 = time.time()

    # --- Build training set ---
    syn = load_synthetic_with_cap(args.hulk_cap, args.random_state)
    print(f"Synthetic loaded: {len(syn):,} rows")
    print("  classes:", syn["Label"].value_counts().to_dict())

    ctu = get_ctu_flows_from_cache()
    print(f"CTU loaded from cache: {len(ctu):,} rows (all 'Bot')")

    diverse_benign = load_diverse_benign()
    print(f"Diverse benign loaded: {len(diverse_benign):,} rows (Day 9b/d)")
    attack_volume = load_attack_volume()
    print(f"Attack-volume loaded: {len(attack_volume):,} rows (Day 9d)")
    if not attack_volume.empty:
        print(f"  per-label: {attack_volume['Label'].value_counts().to_dict()}")
    sandbox_malware = load_sandbox_malware()
    print(f"Sandbox malware loaded: {len(sandbox_malware):,} rows (Day 13)")
    if not sandbox_malware.empty:
        print(f"  per-label: {sandbox_malware['Label'].value_counts().to_dict()}")

    # Stratified split CTU per source PCAP so each scenario contributes
    # to both train and test
    ctu_train_parts = []
    ctu_test_parts = []
    rng = np.random.default_rng(args.random_state)
    for src, g in ctu.groupby("__source"):
        idx = np.arange(len(g))
        rng.shuffle(idx)
        n_train = int(len(g) * args.ctu_train_frac)
        ctu_train_parts.append(g.iloc[idx[:n_train]])
        ctu_test_parts.append(g.iloc[idx[n_train:]])
    ctu_train = pd.concat(ctu_train_parts, ignore_index=True)
    ctu_test = pd.concat(ctu_test_parts, ignore_index=True)
    print(f"CTU train: {len(ctu_train)}, test: {len(ctu_test)}")

    ctu_train["__split_source"] = "ctu_train"
    ctu_test["__split_source"] = "ctu_test"

    # Combined train DataFrame: synthetic + CTU train split + diverse benign
    # + Day 9d attack-volume (high-volume SSH/FTP brute-force) + Day 13
    # sandbox-malware (modern 2024-2026 C2/stealer/RAT captures).
    train_parts = [syn, ctu_train]
    if not diverse_benign.empty:
        diverse_benign["__split_source"] = "diverse_benign"
        train_parts.append(diverse_benign)
    if not attack_volume.empty:
        train_parts.append(attack_volume)
    if not sandbox_malware.empty:
        train_parts.append(sandbox_malware)
    train = pd.concat(train_parts, ignore_index=True, sort=False)
    print(f"\nTotal training rows: {len(train):,}")
    print("Per-label counts:")
    print(train["Label"].value_counts().to_string())

    # Drop classes with <5 samples
    counts = train["Label"].value_counts()
    keep = counts[counts >= 5].index
    dropped = set(counts.index) - set(keep)
    if dropped:
        print(f"Dropping under-represented labels: {sorted(dropped)}")
        train = train[train["Label"].isin(keep)].reset_index(drop=True)

    # Ensure every feature column exists. astype(float) bypasses the
    # PyArrow-backed dtype that parquet returns for cached CTU rows.
    for c in ALL_FEATURES:
        if c not in train.columns:
            train[c] = 0.0
    # Force every feature to numpy float64 in one go
    train[ALL_FEATURES] = (
        train[ALL_FEATURES]
        .apply(lambda s: pd.to_numeric(s, errors="coerce"))
        .astype("float64")
        .replace([np.inf, -np.inf], np.nan)
        .fillna(0.0)
    )

    X = np.ascontiguousarray(train[ALL_FEATURES].to_numpy(dtype=np.float64))
    y = np.asarray(train["Label"].astype(str).values, dtype=object)
    print(f"\nFeature matrix: {X.shape}, dtype={X.dtype}")

    # --- 80/20 train/internal-val split (stratified) ---
    from sklearn.model_selection import train_test_split
    X_tr, X_val, y_tr, y_val = train_test_split(
        X, y, test_size=0.20, random_state=args.random_state, stratify=y,
    )

    # --- Pipeline + XGBoost ---
    pipeline = FeaturePipeline()
    X_tr_p, y_tr_e = pipeline.fit_transform(pd.DataFrame(X_tr, columns=ALL_FEATURES),
                                             pd.Series(y_tr))
    X_val_p, y_val_e = pipeline.transform(pd.DataFrame(X_val, columns=ALL_FEATURES),
                                           pd.Series(y_val))
    print(f"Pipeline kept {len(pipeline.feature_names)} features after variance filter")
    print(f"Classes: {list(pipeline.label_encoder.classes_)}")

    print(f"\n=== XGBoost (Python-only) ===")
    # Day 9b: inverse-frequency sample weights so BENIGN (still a minority
    # at 294 + diverse vs 24K Bot/PortScan/DoS) doesn't get drowned out.
    classes_unique, class_counts = np.unique(y_tr_e, return_counts=True)
    class_weight = {int(c): float(len(y_tr_e) / (len(classes_unique) * cnt))
                    for c, cnt in zip(classes_unique, class_counts)}
    sample_weight = np.array([class_weight[int(c)] for c in y_tr_e],
                              dtype=np.float64)
    print(f"  class_weight: {class_weight}")

    clf = build_xgboost(random_state=args.random_state)
    clf.fit(X_tr_p, y_tr_e, sample_weight=sample_weight)
    print(f"  Train rows: {len(X_tr_p):,}, Val rows: {len(X_val_p):,}")

    from sklearn.metrics import f1_score, accuracy_score, classification_report
    y_val_pred = clf.predict(X_val_p)
    print(f"  Val accuracy: {accuracy_score(y_val_e, y_val_pred):.4f}")
    print(f"  Val F1 weighted: {f1_score(y_val_e, y_val_pred, average='weighted', zero_division=0):.4f}")
    print(f"  Val F1 macro: {f1_score(y_val_e, y_val_pred, average='macro', zero_division=0):.4f}")

    # --- Save artefacts ---
    joblib.dump(clf, OUT_DIR / "xgboost.joblib")
    joblib.dump(pipeline, OUT_DIR / "feature_pipeline.joblib")

    # Save the CTU test split — we need it for eval phase
    ctu_test.to_parquet(OUT_DIR / "ctu_test_holdout.parquet", index=False)

    # Metrics summary
    summary = {
        "n_train": int(len(X_tr)),
        "n_val": int(len(X_val)),
        "n_features_input": int(len(ALL_FEATURES)),
        "n_features_kept": int(len(pipeline.feature_names)),
        "classes": list(pipeline.label_encoder.classes_),
        "val_accuracy": float(accuracy_score(y_val_e, y_val_pred)),
        "val_f1_weighted": float(f1_score(y_val_e, y_val_pred, average="weighted", zero_division=0)),
        "val_f1_macro": float(f1_score(y_val_e, y_val_pred, average="macro", zero_division=0)),
        "val_per_class_report": classification_report(y_val_e, y_val_pred, output_dict=True, zero_division=0),
        "ctu_train_size": int(len(ctu_train)),
        "ctu_test_size": int(len(ctu_test)),
        "synthetic_size": int(len(syn)),
        "diverse_benign_size": int(len(diverse_benign)),
        "attack_volume_size": int(len(attack_volume)),
        "sandbox_malware_size": int(len(sandbox_malware)),
        "class_weight": class_weight,
        "args": vars(args),
        "feature_order": ALL_FEATURES,
    }
    (OUT_DIR / "metrics.json").write_text(
        json.dumps(summary, indent=2, default=str), encoding="utf-8")

    print(f"\nWall time: {(time.time()-t0)/60:.1f} min")
    print(f"Saved: {OUT_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
